---
title: "Gruppe 4"
output: html_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) #Der Code in den Chunks soll im Output stehen
```


```{r benötigte Pakete laden, include=FALSE}

# Einbinden benötigter Bibliotheken und Funktionen
library(tidyverse) #Daten manipulieren (lädt eine Reihe andere Pakete, z.B. readr, dplyr, ggplot2) 


library(psych) #Statistische Methoden

library(lubridate) #Umgang mit Kalender-Daten

#die folgenden Pakete sind beim Daten Explorieren sehr hilfreich... und vermutlich nicht vorinstalliert bei Euch

library(skimr)
library(DataExplorer)
#library(car) 

```

Hier wird 01_Daten einlesen.rmd eingebunden

```{r, child='01_Daten einlesen.rmd'}

```

Hier wird 04_Daten_neuevar_feiertage.Rmd eingebunden
```{r, child='04_Daten_neuevar_feiertage.rmd'}

```


Hier wird 02_Data_cleaning.rmd eingebunden

```{r, child='02_Data_cleaning.rmd'}

```

dataset
dataset_num


Hier wird 03_Model.rmd eingebunden

```{r, child='03_Model.rmd'}

```

Hier wird 04_Vorhersagen.rmd eingebunden

```{r, child='04_Vorhersagen.rmd'}

```


Hier wird 05_SVM.rmd eingebunden

```{r, child='05_SVM.rmd'}

```
