---
title: "Vorbereitung - Daten einlesen und explorieren"
output: html_document
---


# Daten einlesen
Daten werden im Hintergrund hier eingelesen.

```{r Daten einlesen, include=FALSE}
#die include=FALSE Option blendet den Chunk und seine Meldungen aus. Wenn Ihr genauer sehn wollt, was da passiert: Auf TRUE setzen

# Einlesen der Umsatzdaten
umsatzdaten <- read_csv(file.path('Daten','umsatzdaten_gekuerzt.csv',fsep = .Platform$file.sep))
# Erstellung der Variable mit dem Wochentag

ordentlicheWoche <- c('Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag')
umsatzdaten$Wochentag <- factor(weekdays(umsatzdaten$Datum),
levels=ordentlicheWoche)



umsatzdaten$Warengruppe <- factor(umsatzdaten$Warengruppe,
levels = c(1,2,3,4,5,6),
labels = c("Brot", "Broetchen", "Croissant","Konditorei","Kuchen","Saisonbrote"))


kiwo <- read_csv(file.path('Daten','kiwo.csv',fsep = .Platform$file.sep))
wetter <- read_csv(file.path('Daten','wetter.csv',fsep = .Platform$file.sep))




```

```{r Charakteristika der Datensätze anzeigen lassen}

#Anzeigen, welche Variablen in den Datensätzen sind (ohne weitere Information , nur Name) 
#names(umsatzdaten) 
#names(kiwo)
#names(wetter) 
#Mehr Informationen zu den Datensätzen anzeigen
skim(umsatzdaten)
skim(wetter)
skim(kiwo)


#Beobachtung: Bewoelkung hat fehlende Werte.

```

<<<<<<< HEAD
```{r}
#führt Umsatzdaten und Kieler Woche zusammen. Wo keine Werte für kiwo, werden N/A s erzeugt
daten_umsatzdaten_kiwo <- left_join(umsatzdaten, kiwo)
```
```{r}
#führt Kieler Woche und Wetter zusammen
daten_kiwo_wetter <- left_join(kiwo, wetter)
```
```{r}
#führt Umsatzdaten. Kieler Woche und Wetter zusammen
daten_umsatzdaten_kiwo_wetter <- left_join(daten_umsatzdaten_kiwo, daten_kiwo_wetter)
```

=======

# Daten zusammenfügen

```{r Joine kiwo-daten an Umsatzdaten und Wetter-Daten an Umsatzdaten}
umsatzdaten_kiwo<-left_join(umsatzdaten,kiwo, by="Datum")
#names(umsatzdaten_kiwo)
umsatzdaten_kiwo_wetter<-left_join(umsatzdaten_kiwo , wetter, by="Datum")
#names(umsatzdaten_kiwo_wetter)

write.csv(umsatzdaten_kiwo_wetter,file.path('Daten','umsatzdaten_kiwo_wetter.csv',fsep = .Platform$file.sep))



```


<<<<<<< HEAD
>>>>>>> 3ecac330827a418d93e57afece716347ebb860be
=======


>>>>>>> 02812e85cf618b86cbabad65d313243da1e036f2
